version: '3.9'

services:
  app:
    build: .
    container_name: app_dotnet
    ports:
      - 5000:5000
      - 5001:5001
    volumes:
      - ./:/App
    environment:
      ASPNETCORE_HTTP_PORT: "https://+:5001"
      ASPNETCORE_URLS: "http://+:5000"
